name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Lint, Build, and Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn run build
      - name: Test
        env:
          EVM_RPC_URL: ${{ secrets.EVM_RPC_URL }}
        run: yarn test
